reporting: "off"

gui:
  returnImmediately: true
  wrapMainPanel: true

customCommands:
  containers:
    - name: bash
      attach: true
      command: 'docker exec -it {{ .Container.ID }} bash'
      serviceNames: []
    - name: sh
      attach: true
      command: 'docker exec -it {{ .Container.ID }} sh'
      serviceNames: []
    - name: zsh
      attach: true
      command: 'docker exec -it {{ .Container.ID }} zsh'
      serviceNames: []
    - name: dive
      attach: true
      command: 'dive {{ .Container.ID }}'

  images:
    - name: bash
      attach: true
      command: 'docker run -ti {{ .Image.ID }} bash'
      serviceNames: []
    - name: sh
      attach: true
      command: 'docker run -ti {{ .Image.ID }} sh'
      serviceNames: []
    - name: zsh
      attach: true
      command: 'docker run -ti {{ .Image.ID }} zsh'
      serviceNames: []
    - name: dive
      attach: true
      command: 'dive {{ .Image.ID }}'
